version: '3.9'
services:
  dbMysql:
    container_name: dbMysql-freecodecamp
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./dbMysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: $DB_MYSQL_DATABASE
      MYSQL_USER: $DB_MYSQL_USER
      MYSQL_PASSWORD: $DB_MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD: $DB_MYSQL_ROOT_PASSWORD
